### ISSUE TITLE
Issues with installation and running

### ISSUE THREAD

**Issue by LightingMc** [hhj1897/face_parsing#10]
![image](https://user-images.githubusercontent.com/42900802/183485362-065f24c4-f1c3-4649-93a3-679e9438b597.png)

As can be seen in the above repo, I am having a hard time getting the code demo to run. Can you help?

**Comment by yiminglin-ai** [comment]
Please install https://github.com/ibug-group/roi_tanh_warping
________________________________
From: Zaigham Abbas ***@***.***>
Sent: Monday, August 8, 2022 7:08:08 PM
To: hhj1897/face_parsing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hhj1897/face_parsing] Issues with installation and running (Issue #10)

As can be seen in the above repo, I am having a hard time getting the code demo to run. Can you help? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender

ZjQcmQRYFpfptBannerEnd

[image]<https://user-images.githubusercontent.com/42900802/183484327-cdfd06b4-37dc-47c1-8bbb-3341cc8f89c1.png>

As can be seen in the above repo, I am having a hard time getting the code demo to run. Can you help?

**Comment by LightingMc** [comment]
it worked. thanks.
